export interface Service {
  slug: string
  title: string
  shortTitle: string
  displayTitle: string[]
  tagline: string
  description: string
  intro: string[]
  subServices: string[]
  seoKeywords: string[]
}

export const services: Service[] = [
  {
    slug: 'seo',
    title: 'Search Engine Optimization',
    shortTitle: 'SEO',
    displayTitle: ['Rank Higher.', 'Get Found.', 'Grow Faster.'],
    tagline: 'Rank Higher. Get Found. Grow Faster.',
    description:
      'Data-driven SEO strategies that surface your brand to the right audience at precisely the right moment — driving organic traffic and sustainable long-term growth.',
    intro: [
      "In today's digital world, having a website is not enough — your business needs to be visible where your customers are searching. Our professional SEO services help your website rank higher on Google and other major search engines, driving organic traffic and increasing your online visibility.",
      'We offer a complete range of SEO solutions including On-Page SEO, Off-Page SEO, Technical SEO, and Local SEO. Our expert team performs in-depth keyword research, competitor analysis, content optimization, backlink building, and comprehensive website audits to ensure your website meets all Google ranking factors.',
      'Whether you are a startup, small business, or large enterprise, our data-driven SEO strategy helps you attract the right audience, generate quality leads, and grow your revenue. We focus on long-term, sustainable results — not quick fixes.',
    ],
    subServices: [
      'Keyword Research & Strategy',
      'On-Page Optimization (Meta Tags, Headers, Content)',
      'Technical SEO (Site Speed, Mobile Optimization, Crawlability)',
      'Off-Page SEO & Link Building',
      'Local SEO & Google Business Profile Optimization',
      'Monthly SEO Audit & Reporting',
    ],
    seoKeywords: [
      'SEO services',
      'search engine optimization',
      'keyword ranking',
      'organic traffic',
      'on-page SEO',
      'off-page SEO',
      'technical SEO',
      'local SEO',
      'Google ranking',
      'SEO agency',
    ],
  },
  {
    slug: 'website-development',
    title: 'Website Development',
    shortTitle: 'Website Development',
    displayTitle: ['Build a Powerful', 'Online Presence.'],
    tagline: 'Build a Powerful Online Presence with Custom Website Development.',
    description:
      'Custom, responsive websites engineered for performance, security, and conversions — your 24/7 digital storefront built to grow with your business.',
    intro: [
      "Your website is your digital storefront — and first impressions matter. Our professional website development services help businesses create stunning, fast, and fully responsive websites that engage visitors and convert them into customers.",
      'We specialize in custom website design and development for all types of businesses — from informational websites and business portfolios to e-commerce platforms and enterprise web applications. Using the latest technologies including HTML5, CSS3, JavaScript, and React, we build websites that are not only visually appealing but also SEO-friendly, mobile-optimized, and high-performing.',
      'Every website we build is crafted with a focus on user experience (UX), fast loading speed, security, and scalability. We ensure your website aligns perfectly with your brand identity and business goals.',
    ],
    subServices: [
      'Custom Web Design & Development',
      'WordPress Development',
      'E-Commerce Website Development (WooCommerce, Shopify)',
      'Landing Page Design',
      'Website Redesign & Revamp',
      'Website Maintenance & Support',
      'SEO-Friendly Website Structure',
    ],
    seoKeywords: [
      'website development',
      'web design',
      'custom website',
      'responsive website',
      'WordPress development',
      'e-commerce website',
      'business website',
      'website design agency',
      'professional website',
    ],
  },
  {
    slug: 'app-development',
    title: 'App Development',
    shortTitle: 'App Development',
    displayTitle: ['Turn Your Idea Into', 'a Powerful Mobile App.'],
    tagline: 'Turn Your Idea Into a Powerful Mobile App.',
    description:
      'High-performance iOS and Android apps that connect your business with customers anywhere, anytime — built with modern cross-platform technologies.',
    intro: [
      "In a mobile-first world, having a dedicated app for your business is a game-changer. Our expert app development team creates high-performance, user-friendly mobile applications for Android and iOS platforms that help businesses connect with customers anytime, anywhere.",
      'We offer end-to-end mobile app development services — from concept and wireframing to design, development, testing, and deployment. Whether you need a simple business app, an e-commerce app, a service booking app, or a complex enterprise solution, we have the expertise to bring your vision to life.',
      'We use modern technologies like Flutter, React Native, Swift, and Kotlin to build cross-platform and native apps that deliver seamless performance and exceptional user experience.',
    ],
    subServices: [
      'Android App Development',
      'iOS App Development',
      'Cross-Platform App Development (Flutter, React Native)',
      'UI/UX Design for Mobile Apps',
      'App Testing & Quality Assurance',
      'App Store Submission & Optimization (ASO)',
      'App Maintenance & Updates',
      'API Integration',
    ],
    seoKeywords: [
      'app development',
      'mobile app development',
      'Android app',
      'iOS app',
      'Flutter app',
      'React Native',
      'custom app development',
      'business app',
      'mobile application',
    ],
  },
  {
    slug: 'graphic-designing',
    title: 'Graphic Designing',
    shortTitle: 'Graphic Designing',
    displayTitle: ['Creative Designs That', 'Speak Your Brand Language.'],
    tagline: 'Creative Designs That Speak Your Brand Language.',
    description:
      'Visually stunning, strategy-driven design that captures attention, communicates your brand message, and leaves a lasting impression on your audience.',
    intro: [
      'Great design is the foundation of a powerful brand. Our talented graphic design team creates visually stunning designs that capture attention, communicate your brand message, and leave a lasting impression on your audience.',
      'From logo design and brand identity to social media graphics, brochures, banners, packaging, and marketing materials — we offer comprehensive graphic design services tailored to your business needs. We combine creativity with strategy to deliver designs that not only look great but also drive results.',
      'Whether you are launching a new brand or refreshing your existing identity, our designers work closely with you to understand your vision and create designs that truly represent your business.',
    ],
    subServices: [
      'Logo Design & Brand Identity',
      'Social Media Post Design',
      'Business Card & Stationery Design',
      'Brochure, Flyer & Catalogue Design',
      'Banner & Hoarding Design',
      'Packaging Design',
      'Infographic Design',
      'Presentation Design (PowerPoint / Google Slides)',
    ],
    seoKeywords: [
      'graphic design',
      'logo design',
      'brand identity',
      'creative design agency',
      'social media graphics',
      'brochure design',
      'banner design',
      'marketing materials',
      'visual design',
    ],
  },
  {
    slug: 'google-my-business',
    title: 'Google My Business',
    shortTitle: 'Google My Business',
    displayTitle: ['Get Found Locally.', 'Dominate Local Search.'],
    tagline: 'Get Found Locally — Optimize Your Google My Business Profile.',
    description:
      'Full GMB profile optimization that puts your business at the top of local search results and Google Maps — driving more calls, visits, and customers.',
    intro: [
      "When customers search for businesses near them, Google My Business is the first thing they see. A well-optimized Google Business Profile helps your business appear in local search results and Google Maps, driving more foot traffic, calls, and website visits.",
      'Our Google My Business optimization services ensure your business stands out in local searches. We set up, verify, and fully optimize your GMB profile so you can attract more local customers and stay ahead of competitors.',
      'From accurate business information and keyword-rich descriptions to photo uploads, regular posts, and review management — we handle everything to maximize your local visibility and credibility.',
    ],
    subServices: [
      'GMB Profile Setup & Verification',
      'Business Information Optimization (Name, Address, Phone, Hours)',
      'Keyword-Rich Business Description',
      'Category & Attribute Optimization',
      'Photo & Video Uploads',
      'Google Posts & Updates Management',
      'Review Management & Response',
      'Q&A Management',
      'GMB Insights & Performance Reporting',
      'Local Citation Building',
    ],
    seoKeywords: [
      'Google My Business',
      'GMB optimization',
      'local SEO',
      'Google Business Profile',
      'local business listing',
      'Google Maps ranking',
      'local search optimization',
      'business listing management',
    ],
  },
  {
    slug: 'google-meta-ads',
    title: 'Google & Meta Ads',
    shortTitle: 'Google & Meta Ads',
    displayTitle: ['Reach Your Audience', 'With Powerful', 'Paid Advertising.'],
    tagline: 'Reach Your Target Audience with Powerful Paid Advertising.',
    description:
      'High-performance Google and Meta ad campaigns that put your brand in front of the right audience at the right moment — maximizing ROAS and minimizing wasted spend.',
    intro: [
      "Want instant visibility and faster results? Our Google Ads and Meta Ads (Facebook & Instagram Ads) management services help you reach your ideal customers exactly when they are ready to buy — driving qualified traffic, leads, and sales for your business.",
      'We create, manage, and optimize high-performance ad campaigns across Google Search, Display, YouTube, Facebook, and Instagram. Our certified ad specialists use advanced targeting, compelling ad creatives, and data-driven strategies to maximize your return on ad spend (ROAS) and minimize wasted budget.',
      'Whether your goal is brand awareness, lead generation, e-commerce sales, or app installs — we design custom ad strategies that deliver measurable results.',
    ],
    subServices: [
      'Google Search Ads (PPC)',
      'Google Display Ads',
      'Google Shopping Ads',
      'YouTube Video Ads',
      'Facebook & Instagram Ad Campaigns',
      'Retargeting / Remarketing Campaigns',
      'Audience Research & Targeting',
      'Ad Copywriting & Creative Design',
      'Landing Page Optimization',
      'Campaign Monitoring & A/B Testing',
      'Monthly Performance Reports',
    ],
    seoKeywords: [
      'Google Ads',
      'Meta Ads',
      'Facebook Ads',
      'Instagram Ads',
      'paid advertising',
      'PPC management',
      'digital ads',
      'Google AdWords',
      'performance marketing',
      'paid social media ads',
    ],
  },
  {
    slug: 'social-media-management',
    title: 'Social Media Management',
    shortTitle: 'Social Media',
    displayTitle: ['Build Your Brand.', 'Grow Your Audience.'],
    tagline: 'Build Your Brand. Grow Your Audience. Engage Your Community.',
    description:
      'End-to-end social media management that builds a strong, consistent brand presence across every major platform — growing followers, boosting engagement, and driving real business results.',
    intro: [
      "Social media is where your customers spend their time — and your brand needs to be there too. Our social media management services help businesses build a strong, consistent, and engaging presence across all major platforms including Facebook, Instagram, LinkedIn, Twitter, and YouTube.",
      'We handle everything from content creation and scheduling to community management and performance analysis. Our team of social media experts crafts platform-specific strategies that grow your followers, boost engagement, and drive real business results.',
      'We create scroll-stopping content — graphics, captions, reels, and stories — that aligns with your brand voice and resonates with your target audience.',
    ],
    subServices: [
      'Social Media Strategy & Planning',
      'Content Creation (Graphics, Videos, Captions)',
      'Content Calendar Management',
      'Daily Posting & Scheduling',
      'Community Management & Audience Engagement',
      'Hashtag Research & Optimization',
      'Facebook & Instagram Page Management',
      'LinkedIn Business Page Management',
      'Monthly Analytics & Performance Reporting',
      'Social Media Account Setup & Branding',
    ],
    seoKeywords: [
      'social media management',
      'social media marketing',
      'Facebook management',
      'Instagram marketing',
      'LinkedIn marketing',
      'social media strategy',
      'content calendar',
      'social media agency',
    ],
  },
  {
    slug: 'email-marketing',
    title: 'Email Marketing',
    shortTitle: 'Email Marketing',
    displayTitle: ['Connect, Nurture', '& Convert.'],
    tagline: 'Connect, Nurture & Convert with Powerful Email Marketing.',
    description:
      'Targeted, personalized email campaigns that land in inboxes, nurture leads, and drive conversions — consistently delivering one of the highest ROIs in digital marketing.',
    intro: [
      "Email marketing remains one of the highest-ROI digital marketing channels available today. Our professional email marketing services help businesses build meaningful relationships with their audience, nurture leads, and drive conversions — all through targeted, personalized email campaigns.",
      'We design, write, and manage end-to-end email marketing campaigns that land in inboxes (not spam folders) and compel readers to take action. From welcome emails and promotional newsletters to automated drip sequences and re-engagement campaigns — we create email strategies that deliver real results.',
      'Our data-driven approach ensures your emails reach the right people at the right time with the right message, boosting open rates, click-through rates, and revenue.',
    ],
    subServices: [
      'Email Marketing Strategy & Planning',
      'Email List Building & Segmentation',
      'Custom Email Template Design',
      'Copywriting & Content Creation',
      'Campaign Setup & Scheduling',
      'Email Automation & Drip Sequences',
      'A/B Testing (Subject Lines, CTAs, Design)',
      'Deliverability Optimization',
      'Performance Tracking & Analytics',
      'Monthly Reporting',
    ],
    seoKeywords: [
      'email marketing',
      'email campaigns',
      'email automation',
      'newsletter marketing',
      'email marketing services',
      'drip campaigns',
      'email strategy',
      'lead nurturing',
      'bulk email marketing',
    ],
  },
  {
    slug: 'video-editing',
    title: 'Video Editing',
    shortTitle: 'Video Editing',
    displayTitle: ['Professional Video', 'That Tells Your', 'Brand Story.'],
    tagline: 'Professional Video Editing That Tells Your Brand Story.',
    description:
      'Polished, impactful video production that transforms raw footage into compelling visual stories — capturing audiences and driving measurable results across every platform.',
    intro: [
      "In a world where video content dominates digital platforms, high-quality video editing can make the difference between a scroll and a stop. Our professional video editing services help brands, businesses, and content creators produce polished, engaging, and impactful videos that captivate audiences and drive results.",
      'Whether you need YouTube videos, Instagram Reels, product promotional videos, corporate presentations, or event highlight videos — our skilled video editors transform raw footage into compelling visual stories using industry-leading tools like Adobe Premiere Pro and After Effects.',
      'We focus on storytelling, pacing, color grading, sound design, and visual effects to deliver videos that reflect your brand quality and connect with your audience.',
    ],
    subServices: [
      'YouTube Video Editing',
      'Instagram Reels & Short-Form Video Editing',
      'Promotional & Advertisement Video Editing',
      'Corporate & Training Video Editing',
      'Event Highlight Video Editing',
      'Intro & Outro Design',
      'Motion Graphics & Animations',
      'Color Grading & Color Correction',
      'Subtitles & Captions',
      'Thumbnail Design',
    ],
    seoKeywords: [
      'video editing',
      'professional video editing',
      'YouTube video editing',
      'social media video editing',
      'promotional video',
      'reel editing',
      'corporate video editing',
      'video production services',
    ],
  },
  {
    slug: 'content-writing',
    title: 'Content Writing',
    shortTitle: 'Content Writing',
    displayTitle: ['Words That Engage,', 'Inform & Convert.'],
    tagline: 'Words That Engage, Inform & Convert.',
    description:
      'SEO-optimized, original content that speaks directly to your audience, builds brand authority, and drives action — across every format and channel.',
    intro: [
      "Great content is the backbone of every successful digital marketing strategy. Our professional content writing services help businesses communicate their message clearly, engage their target audience, and rank higher on search engines through well-researched, SEO-optimized, and compelling content.",
      'From website copy and blog articles to social media content, product descriptions, press releases, and email newsletters — we create content that speaks directly to your audience and drives action. Our team of experienced writers understands how to blend creativity with SEO best practices to produce content that both humans and search engines love.',
      'Every piece of content we create is original, plagiarism-free, thoroughly researched, and aligned with your brand voice and business objectives.',
    ],
    subServices: [
      'Website Content Writing (Home, About, Services, etc.)',
      'SEO Blog Writing & Article Writing',
      'Social Media Content & Captions',
      'Product Descriptions',
      'Press Release Writing',
      'Email Newsletter Content',
      'Case Studies & Whitepapers',
      'Ad Copywriting (Google Ads, Facebook Ads)',
      'Proofreading & Editing',
      'Content Strategy & Planning',
    ],
    seoKeywords: [
      'content writing',
      'SEO content writing',
      'blog writing',
      'website content',
      'copywriting',
      'article writing',
      'content marketing',
      'professional content writer',
      'social media content',
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug)
}
